import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {AreaChart,Area,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import {AlertCircle, Cloud, DollarSign, Download, RefreshCw, Search, Server, Sparkles, TrendingDown} from 'lucide-react';
import './styles.css';
const api='/api/v1', money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n||0);
const request=async path=>{const r=await fetch(`${api}/${path}`);if(!r.ok)throw new Error();return r.json()};
function App(){const [summary,setSummary]=useState({}),[trends,setTrends]=useState([]),[items,setItems]=useState([]),[resources,setResources]=useState([]),[loading,setLoading]=useState(true),[syncing,setSyncing]=useState(false),[error,setError]=useState(''),[query,setQuery]=useState(''),[filter,setFilter]=useState('ALL'),[notice,setNotice]=useState('');
const load=async()=>{setLoading(true);setError('');try{const [s,t,i,r]=await Promise.all(['dashboard/summary','dashboard/trends','recommendations','resources'].map(request));setSummary(s);setTrends(t);setItems(i);setResources(r)}catch{setError('Unable to refresh cloud data. Check that the API is running and try again.')}finally{setLoading(false)}};useEffect(()=>{load()},[]);
const update=async(id,status)=>{try{await fetch(`${api}/recommendations/${id}/status`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status})});setNotice('Recommendation moved to In progress.');await load()}catch{setError('Could not update this recommendation.')}};
const syncCosts=async()=>{setSyncing(true);try{const result=await fetch(`${api}/costs/sync`,{method:'POST'}).then(r=>r.json());setNotice(result.status==='SYNCED'?'Live Azure cost data imported.':result.message||'Demo cost data is active.');await load()}catch{setError('Could not sync Azure costs.')}finally{setSyncing(false)}};
const shown=useMemo(()=>resources.filter(r=>(filter==='ALL'||r.resourceType===filter)&&`${r.name} ${r.region}`.toLowerCase().includes(query.toLowerCase())),[resources,filter,query]);
return <main><nav><span className="brand"><Cloud/> FinOps Lens</span><span className="pill">{summary.costSource==='azure-cost-management'?'Azure cost data':'Demo data'} <i/></span></nav><header><div><p className="eyebrow">CLOUD COST INTELLIGENCE</p><h1>Spend less. Build more.</h1><p className="sub">A clear view of cloud spend, utilization, and your fastest savings wins.</p></div><div className="header-actions"><a className="export" href={`${api}/reports/export`}><Download size={15}/> Export CSV</a><button onClick={syncCosts} disabled={syncing}>{syncing?'Syncing…':'Sync Azure costs'}</button><button onClick={load} disabled={loading}><RefreshCw size={16} className={loading?'spin':''}/>{loading?'Refreshing':'Refresh data'}</button></div></header>
{error&&<div className="message error"><AlertCircle size={18}/>{error}<button onClick={load}>Retry</button></div>}{notice&&<div className="message success">{notice}<button onClick={()=>setNotice('')}>Dismiss</button></div>}
<section className="cards"><Card icon={<DollarSign/>} label="Monthly spend" value={money(summary.monthlySpend)} hint="6.2% below last month"/><Card icon={<TrendingDown/>} label="Potential savings" value={money(summary.potentialSavings)} hint="Across active recommendations" accent/><Card icon={<Server/>} label="Resources scanned" value={summary.resources||0} hint="Compute and storage"/><Card icon={<Sparkles/>} label="Open actions" value={summary.openRecommendations||0} hint="Ready for review"/></section>
<section className="grid"><article className="panel chart"><div><p className="eyebrow">SPEND TRAJECTORY</p><h2>Cost is moving in the right direction</h2></div><ResponsiveContainer width="100%" height={260}><AreaChart data={trends}><defs><linearGradient id="g" x1="0" x2="0" y1="0" y2="1"><stop stopColor="#37d59a" stopOpacity=".45"/><stop offset="1" stopColor="#37d59a" stopOpacity="0"/></linearGradient></defs><XAxis dataKey="month"/><YAxis tickFormatter={x=>`$${x}`}/><Tooltip formatter={x=>money(x)}/><Area type="monotone" dataKey="spend" stroke="#37d59a" strokeWidth={3} fill="url(#g)"/></AreaChart></ResponsiveContainer></article><article className="panel"><p className="eyebrow">TOP OPPORTUNITIES</p><h2>Money left on the table</h2><div className="opportunities">{items.slice(0,4).map(x=><div className="opportunity" key={x.id}><span className={`dot ${x.impact.toLowerCase()}`}/><div><b>{x.title}</b><small>{x.resourceName} · {x.category} · {x.status.replace('_',' ')}</small></div><strong>{money(x.monthlySavings)}/mo</strong>{x.status==='OPEN'?<button className="tiny" onClick={()=>update(x.id,'IN_PROGRESS')}>Start</button>:<span className="status">In progress</span>}</div>)}</div></article></section>
<section className="panel table"><div className="section-title"><div><p className="eyebrow">RESOURCE INVENTORY</p><h2>Utilization at a glance</h2></div><span>{loading?'Updating…':`${shown.length} of ${resources.length} resources`}</span></div><div className="toolbar"><label className="search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search resources or regions"/></label><select value={filter} onChange={e=>setFilter(e.target.value)} aria-label="Filter by resource type"><option value="ALL">All resource types</option><option value="Virtual Machine">Virtual machines</option><option value="Storage Account">Storage accounts</option><option value="Managed Disk">Managed disks</option></select></div><div className="rows">{shown.map(r=><div className="row" key={r.id}><b>{r.name}</b><span>{r.resourceType}</span><span>{r.region}</span><span><em style={{width:`${r.utilizationPercent}%`}}/> {r.utilizationPercent}%</span><strong>{money(r.monthlyCost)}</strong></div>)}{!loading&&!shown.length&&<p className="empty">No resources match those filters.</p>}</div></section></main>}
function Card({icon,label,value,hint,accent}){return <article className={'card '+(accent?'accent':'')}><div className="icon">{icon}</div><p>{label}</p><h2>{value}</h2><small>{hint}</small></article>}createRoot(document.getElementById('root')).render(<App/>);
