import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {AreaChart,Area,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import {Cloud, DollarSign, Server, Sparkles, TrendingDown} from 'lucide-react';
import './styles.css';
const api='/api/v1';
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n||0);
function App(){const [summary,setSummary]=useState({});const [trends,setTrends]=useState([]);const [items,setItems]=useState([]);const [resources,setResources]=useState([]);const [loading,setLoading]=useState(true);
 const load=async()=>{setLoading(true);try{const [s,t,i,r]=await Promise.all(['dashboard/summary','dashboard/trends','recommendations','resources'].map(x=>fetch(`${api}/${x}`).then(x=>x.json())));setSummary(s);setTrends(t);setItems(i);setResources(r)}finally{setLoading(false)}};useEffect(()=>{load()},[]);
 const update=async(id,status)=>{await fetch(`${api}/recommendations/${id}/status`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status})});load()};
 return <main><nav><span className="brand"><Cloud/> FinOps Lens</span><span className="pill">Azure connected <i/></span></nav><header><div><p className="eyebrow">CLOUD COST INTELLIGENCE</p><h1>Spend less. Build more.</h1><p className="sub">A clear view of cloud spend, utilization, and your fastest savings wins.</p></div><button onClick={load}>Refresh data</button></header>
 <section className="cards"><Card icon={<DollarSign/>} label="Monthly spend" value={money(summary.monthlySpend)} hint="6.2% below last month"/><Card icon={<TrendingDown/>} label="Potential savings" value={money(summary.potentialSavings)} hint="Across active recommendations" accent/><Card icon={<Server/>} label="Resources scanned" value={summary.resources||0} hint="Compute and storage"/><Card icon={<Sparkles/>} label="Open actions" value={summary.openRecommendations||0} hint="Ready for review"/></section>
 <section className="grid"><article className="panel chart"><div><p className="eyebrow">SPEND TRAJECTORY</p><h2>Cost is moving in the right direction</h2></div><ResponsiveContainer width="100%" height={260}><AreaChart data={trends}><defs><linearGradient id="g" x1="0" x2="0" y1="0" y2="1"><stop stopColor="#37d59a" stopOpacity=".45"/><stop offset="1" stopColor="#37d59a" stopOpacity="0"/></linearGradient></defs><XAxis dataKey="month"/><YAxis tickFormatter={x=>`$${x}`}/><Tooltip formatter={x=>money(x)}/><Area type="monotone" dataKey="spend" stroke="#37d59a" strokeWidth={3} fill="url(#g)"/></AreaChart></ResponsiveContainer></article>
 <article className="panel"><p className="eyebrow">TOP OPPORTUNITIES</p><h2>Money left on the table</h2><div className="opportunities">{items.slice(0,4).map(x=><div className="opportunity" key={x.id}><span className="dot"/><div><b>{x.title}</b><small>{x.resourceName} · {x.category}</small></div><strong>{money(x.monthlySavings)}/mo</strong><button className="tiny" onClick={()=>update(x.id,'IN_PROGRESS')}>Act</button></div>)}</div></article></section>
 <section className="panel table"><div className="section-title"><div><p className="eyebrow">RESOURCE INVENTORY</p><h2>Utilization at a glance</h2></div><span>{loading?'Updating…':`${resources.length} resources`}</span></div><div className="rows">{resources.map(r=><div className="row" key={r.id}><b>{r.name}</b><span>{r.resourceType}</span><span>{r.region}</span><span><em style={{width:`${r.utilizationPercent}%`}}/> {r.utilizationPercent}%</span><strong>{money(r.monthlyCost)}</strong></div>)}</div></section></main>}
function Card({icon,label,value,hint,accent}) {return <article className={'card '+(accent?'accent':'')}><div className="icon">{icon}</div><p>{label}</p><h2>{value}</h2><small>{hint}</small></article>};createRoot(document.getElementById('root')).render(<App/>);
